### ISSUE TITLE
Issue on react-native run-android

### ISSUE THREAD

**Issue by theredfoxfire** [kodefox/class-autobind#1]
I got this error when try to run in Android virtual device

![ScreenShoot](http://s32.postimg.org/lclpbewjp/Screen_Shot_2016_05_19_at_12_47_41_PM.png)

Is there an issue from my code or something different?

**Comment by sstur** [comment]
I think that might be an issue in `class-autobind` I'll take a closer look..

**Comment by sstur** [comment]
OK. I fixed this issue in v0.1.3. It was related to Babel which expects `Symbol.iterator` to exist on `Array.prototype` in order for `for (item of array) {...}` to work. I have flipped Babel into "loose mode" which seems to fix the problem.

Let me know if there are any other issues.

Thanks!
